'use client';
import { useEffect,useState } from 'react';
import { api,Product,ProductCard } from './store';
import { money } from '@/lib/format';
type User={name:string;email:string;mobile:string;role:string};
type Order={id:string;status:string;paymentStatus:string;total:number;createdAt:string;items:{id:string;name:string;quantity:number;price:number}[]};
type Address={id:string;name:string;mobile:string;province:string;city:string;address:string;postalCode:string};
export function AuthForm({admin=false}:{admin?:boolean}){const [register,setRegister]=useState(false),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);return <div className="auth-card"><p className="eyebrow">MAHNESHAN</p><h1>{admin?'ورود مدیریت':register?'به ماه‌نشان بپیوندید':'دوباره خوش آمدید'}</h1><form className="form" onSubmit={async e=>{e.preventDefault();setBusy(true);try{const data=Object.fromEntries(new FormData(e.currentTarget));const r=await api(register?'auth/register':'auth/login',data);if(admin&&r.role!=='ADMIN')throw new Error('حساب شما دسترسی مدیریت ندارد');window.location.href=admin?'/admin':'/account';}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}}>{register&&<label>نام و نام خانوادگی<input name="name" required autoComplete="name"/></label>}<label>ایمیل<input name="email" type="email" required dir="ltr" autoComplete="email"/></label><label>گذرواژه<input name="password" type="password" required minLength={10} dir="ltr" autoComplete={register?'new-password':'current-password'}/></label><p className="feedback" role="alert">{message}</p><button className="primary" disabled={busy}>{busy?'در حال بررسی…':register?'ساخت حساب':'ورود'}</button></form>{!admin&&<button className="text-button" onClick={()=>setRegister(!register)}>{register?'قبلاً ثبت‌نام کرده‌اید؟ ورود':'حساب ندارید؟ ثبت‌نام'}</button>}</div>;}
export function Account(){const [user,setUser]=useState<User|null|undefined>(undefined),[tab,setTab]=useState('orders'),[orders,setOrders]=useState<Order[]>([]),[wishlist,setWishlist]=useState<{id:string;product:Product}[]>([]),[addresses,setAddresses]=useState<Address[]>([]),[message,setMessage]=useState('');
useEffect(()=>{setTab(new URLSearchParams(window.location.search).get('tab')||'orders');api('me').then(setUser).catch(e=>setMessage(e.message));},[]);
useEffect(()=>{if(user){api('account/orders').then(setOrders).catch(e=>setMessage(e.message));api('wishlist').then(setWishlist).catch(e=>setMessage(e.message));api('account/addresses').then(setAddresses).catch(e=>setMessage(e.message));}},[user]);
if(user===undefined)return <main className="empty">{message||'در حال بارگذاری…'}</main>;if(!user)return <AuthForm/>;
return <main className="section"><div className="section-title"><div><p className="eyebrow">YOUR MAHNESHAN</p><h1>{user.name}، خوش آمدید</h1></div><button className="text-button" onClick={async()=>{await api('auth/logout',{});window.location.reload();}}>خروج از حساب</button></div><div className="tabs">{[['orders','سفارش‌ها'],['wishlist','علاقه‌مندی‌ها'],['addresses','نشانی‌ها'],['profile','اطلاعات حساب']].map(([k,v])=><button key={k} className={tab===k?'active':''} onClick={()=>setTab(k)}>{v}</button>)}</div><p role="status">{message}</p>{tab==='orders'&&(!orders.length?<div className="empty">هنوز سفارشی ثبت نکرده‌اید.</div>:orders.map(o=><details className="order-box" key={o.id}><summary>سفارش {o.id.slice(-8)} · {new Date(o.createdAt).toLocaleDateString('fa-IR')} · {money(o.total)} · {o.status}</summary><p>وضعیت پرداخت: {o.paymentStatus==='PAID'?'پرداخت‌شده':'پرداخت‌نشده'}</p>{o.items.map(i=><p key={i.id}>{i.name} × {i.quantity} — {money(i.price*i.quantity)}</p>)}</details>))}{tab==='wishlist'&&<div className="product-grid home-grid">{wishlist.length?wishlist.map(w=><ProductCard key={w.id} product={w.product}/>):<p>فهرست علاقه‌مندی‌های شما خالی است.</p>}</div>}{tab==='profile'&&<form className="form narrow" onSubmit={async e=>{e.preventDefault();try{await api('account/profile',Object.fromEntries(new FormData(e.currentTarget)));setMessage('اطلاعات ذخیره شد');}catch(e){setMessage((e as Error).message);}}}><label>نام<input name="name" defaultValue={user.name} required/></label><label>موبایل<input name="mobile" defaultValue={user.mobile} pattern="09[0-9]{9}" required/></label><p>{user.email}</p><button className="primary">ذخیره اطلاعات</button></form>}{tab==='addresses'&&<><div className="address-list">{addresses.map(a=><div className="order-box" key={a.id}><h3>{a.name} · {a.city}</h3><p>{a.province}، {a.address} · {a.postalCode}</p><button onClick={async()=>{try{setAddresses(await api('account/addresses/'+a.id,undefined,'DELETE'));}catch(e){setMessage((e as Error).message);}}}>حذف نشانی</button></div>)}</div><h2>نشانی تازه</h2><form className="form form-grid" onSubmit={async e=>{e.preventDefault();const form=e.currentTarget;try{setAddresses(await api('account/addresses',Object.fromEntries(new FormData(form))));setMessage('نشانی ذخیره شد');form.reset();}catch(e){setMessage((e as Error).message);}}}>{[['name','نام گیرنده'],['mobile','موبایل'],['province','استان'],['city','شهر'],['address','نشانی'],['postalCode','کد پستی']].map(([n,l])=><label key={n}>{l}<input name={n} required/></label>)}<button className="primary">ذخیره نشانی</button></form></>}</main>;}
