import EmbeddedPostgres from 'embedded-postgres';
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { randomBytes } from 'node:crypto';
import path from 'node:path';
mkdirSync('.data',{recursive:true});
const configPath='.data/db-config.json';
const config=existsSync(configPath)?JSON.parse(readFileSync(configPath,'utf8')):{password:randomBytes(24).toString('hex'),port:55432};
writeFileSync(configPath,JSON.stringify(config));
const databaseDir=path.resolve('.data/postgres');
const pg=new EmbeddedPostgres({databaseDir,user:'postgres',password:config.password,port:config.port,persistent:true,initdbFlags:['--encoding=UTF8','--locale=C']});
if(!existsSync(path.join(databaseDir,'PG_VERSION')))await pg.initialise();
await pg.start();
const client=pg.getPgClient();await client.connect();
const result=await client.query("SELECT 1 FROM pg_database WHERE datname='mahneshan'");
if(!result.rows.length)await client.query('CREATE DATABASE mahneshan');
await client.end();
if(!existsSync('.env'))writeFileSync('.env',`DATABASE_URL="postgresql://postgres:${config.password}@127.0.0.1:${config.port}/mahneshan?schema=public"\nAPP_URL="http://localhost:3000"\nCOOKIE_SECURE="false"\nSEED_ADMIN_EMAIL="admin@mahneshan.local"\nSEED_ADMIN_PASSWORD="CHANGE_THIS_BEFORE_SEEDING"\n`);
console.log('PostgreSQL ready on 127.0.0.1:'+config.port);
const stop=async()=>{await pg.stop();process.exit(0);};
process.on('SIGINT',stop);process.on('SIGTERM',stop);
setInterval(()=>{},60000);
